Kill JVM/Tomcat on OutOfMemoryError
After an OutOfMemoryError, the JVM and Tomcat instance are considered
unreliable, and it's best to kill the process. In this commit, we
introduce a script `kill-pxf.sh` in the pxf-service/bin that handles
this situation.

A sleep is used in `kill-pxf.sh` to allow the JVM to log and bubble up
to the user the OutOfMemoryError.

For testing we have an OutOfMemoryFragmenter that creates a very large
list, running into the memory limits. This should bring the app down,
and we sleep for 3 seconds to give the app time to be brought down, then
check that we get Failed to connect error.

We also support the user not killing the JVM on OOM by setting the
environment variable PXF_OOM_KILL to false in `$PXF_CONF/conf/pxf-env.sh`.

The user can also set PXF_OOM_DUMP_PATH to a directory or a file path to
get a heap dump on OOM. If it's a directory, Tomcat will make a heap
dump file called `java_pid<PID>.hprof` at that directory.

We give the user a NOTICE when they set PXF_OOM_DUMP_PATH informing them
that they need enough disk space to hold a heap dump file there.

Co-authored-by: Oliver Albertini <oalbertini@pivotal.io>
Co-authored-by: Alex Denissov <adenissov@pivotal.io>
Co-authored-by: Francisco Guerrero <aguerrero@pivotal.io>
Co-authored-by: Shivram Mani <smani@pivotal.io>
Co-authored-by: Lav Jain <ljain@pivotal.io>

diff --git a/server/pxf-service/src/scripts/pxf-service b/server/pxf-service/src/scripts/pxf-service
--- a/server/pxf-service/src/scripts/pxf-service
+++ b/server/pxf-service/src/scripts/pxf-service
@@ -134,6 +134,7 @@ function createInstance()
 
     # copy configuration files into instance
     cp ${tomcat_templates}/bin/setenv.sh ${instance_root}/${instance_name}/bin/setenv.sh
+    cp ${tomcat_templates}/bin/kill-pxf.sh ${instance_root}/${instance_name}/bin/kill-pxf.sh
     cp ${tomcat_templates}/conf/logging.properties ${instance_root}/${instance_name}/conf/.
     cp ${tomcat_templates}/conf/server.xml ${instance_root}/${instance_name}/conf/.
     cp ${tomcat_templates}/conf/web.xml ${instance_root}/${instance_name}/conf/.
@@ -210,23 +211,6 @@ function instanceExists()
 
     ${instance_root}/${instance_name}/bin/catalina.sh version > /dev/null 2>&1
     return $?
-}
-
-function commandWebapp()
-{
-    command=$1
-    if [[ ${PXF_DEBUG} == "true" && ${command} == "start" ]]; then
-        command="jpda $command"
-    fi
-    pushd ${instance_root} > /dev/null
-
-    # Run command as a current user
-    ${instance_root}/${instance_name}/bin/catalina.sh ${command}
-
-    if (( $? != 0 )); then
-        return 1
-    fi
-    popd > /dev/null
 }
 
 function createLogsDir()
@@ -362,7 +346,7 @@ function doInit()
 }
 
 #
-# doStart handles start command
+# doStart handles start commands
 # command is executed as the current user
 #
 # after start, uses checkWebapp to verify the PXF webapp was loaded
@@ -370,28 +354,31 @@ function doInit()
 #
 function doStart()
 {
-    instanceExists
-    if (( $? != 0 )); then
-        fail "Can't find PXF instance, maybe call init?"
+    local flags=()
+    if ! instanceExists; then
+        fail 'Cannot find PXF instance, maybe call init?'
     fi
     get_environment
-    commandWebapp start || return 1
+    [[ $PXF_DEBUG == true ]] && flags+=(jpda)
+    flags+=(start)
+    "${instance_root}/${instance_name}/bin/catalina.sh" "${flags[@]}" || return 1
     checkWebapp 300 || return 1
 }
 
 #
-# doStart handles stop command
+# doStop handles stop commands
 # command is executed as the current user
 #
+# the -force flag is passed to catalina.sh to enable force-stopping
+# the JVM
 #
 function doStop()
 {
-    instanceExists
-    if (( $? != 0 )); then
-        fail "Can't find PXF instance, maybe call init?"
+    if ! instanceExists; then
+        fail 'Cannot find PXF instance, maybe call init?'
     fi
     get_environment
-    commandWebapp stop || return 1
+    "${instance_root}/${instance_name}/bin/catalina.sh" stop -force || return 1
 }
 
 function doStatus()
