pxf cluster init: enforce JAVA_HOME is set
Sometimes users want to use a specific version of Java with PXF. In the
current world, initializing PXF can become awkward. We would ask the
user to temporarily set JAVA_HOME in ~/.bashrc to perform the init (or
pxf-env-default.sh, which users shouldn't touch). Then after init, we
would ask them to manually adjust JAVA_HOME in $PXF_CONF/conf/pxf-env.sh
for their custom PXF value and optionally switch back in ~/.bashrc.

This PR proposes a better scenario where we enforce that JAVA_HOME is
valid in pxf cluster init by passing from the command's environment to
the remote hosts. Command then looks like this:

`JAVA_HOME=/correct/java/home pxf cluster init`

The pxf-service script also edits $PXF_CONF/conf/pxf-env.sh to make sure
that PXF will always have the correct value of JAVA_HOME. Users can thus
have whatever they like in their startup scripts, etc. for JAVA_HOME.

Also pxf-service stops telling users to edit pxf-env-default.sh.

Authored-by: Oliver Albertini <oalbertini@pivotal.io>

diff --git a/server/pxf-service/src/scripts/pxf-service b/server/pxf-service/src/scripts/pxf-service
--- a/server/pxf-service/src/scripts/pxf-service
+++ b/server/pxf-service/src/scripts/pxf-service
@@ -103,11 +103,11 @@ function get_environment()
 
 }
 
-checkJavaHome()
+function checkJavaHome()
 {
     # validate JAVA_HOME
     if [[ ! -x ${JAVA_HOME}/bin/java ]]; then
-        fail "\$JAVA_HOME=$JAVA_HOME is invalid. Set \$JAVA_HOME in ~/.bashrc or $default_env_script on all Greenplum hosts."
+        fail "\$JAVA_HOME=$JAVA_HOME is invalid. Set \$JAVA_HOME in your environment before initializing PXF."
     fi
 }
 
@@ -370,10 +370,16 @@ function doInit()
     checkJavaHome
     generatePrivateClasspath || return 1
     generateUserConfigs || return 1
+    editPxfEnvSh || return 1
     createInstance || return 1
     deployWebapp || return 1
     createLogsDir || return 1
     createRunDir  || return 1
+}
+
+function editPxfEnvSh()
+{
+	sed -i.bak -e "s|.*JAVA_HOME=.*|JAVA_HOME=${JAVA_HOME}|g" "${PXF_CONF}/conf/pxf-env.sh" && rm "${PXF_CONF}/conf/pxf-env.sh.bak"
 }
 
 #
