Continuous Integration: independent release process
This commit introduces several new pipelines to aid a PXF release
process independent of any underlying SQL database. This commit thus
includes scripts for making and managing a PXF RPM, which includes the C
extension, whose code now lives under external-table/. These are the new
pipelines:

* pivnet_artifacts: a pipeline that fetches releases of GPDB from
  PivNet, aka TanzuNet
* pxf-build: pipeline that builds and releases new PXF artifacts
* dev-pxf-build: dev version of pxf-build, much abbreviated
* pxf-certification: pipeline that tests existing PXF artifacts against
  new versions of Greenplum
* pxf_pr_pipeline: new PR pipeline which uses the new build process

Version is now managed at the top level, in a file `version`. By
changing this file to a non-SNAPSHOT version, we can create a release
using the pxf-build pipeline. This causes a new tag/release to be
triggered on GitHub (Releases API), as well as a new SNAPSHOT version to
be committed.

Further, by uploading an OSL file to the appropriate cloud location,
we trigger publication of our release to the Release Engineering team.

Along with an independent release, we are now also installing PXF not
under GPHOME but separately in PXF_HOME. Thus this commit also has
changes to the PXF CLI to reflect the new install location. This
includes a new command called `pxf [cluster] register` to re-install the
PXF C extension under GPHOME.

Other noteworthy changes include:

* The new pipelines make use of smaller images that don't include PXF
  dependencies, but instead pull in those dependencies via tarballs that
  are pre-built.
* The new pattern for setting pipelines is to have targets in
  concourse/Makefile.
* Cloud tests have been hardened to reduce flakiness
* In CI scripts we source ~gpadmin/.pxfrc which is cached on each image
* Slack integrations have been added for pxf-certification, pxf-build,
  and dev-pxf-build pipelines

Co-authored-by: Oliver Albertini <oalbertini@vmware.com>
Co-authored-by: Alexander Denissov <adenissov@pivotal.io>
Co-authored-by: Francisco Guerrero <aguerrero@pivotal.io>

diff --git a/automation/Makefile b/automation/Makefile
--- a/automation/Makefile
+++ b/automation/Makefile
@@ -18,9 +18,6 @@ ifneq "$(GROUP)" ""
 	MAVEN_TEST_OPTS+= -Dgroups=$(GROUP)
 endif
 
-ifeq "$(PXF_HOME)" ""
-	PXF_HOME=$(GPHOME)/pxf
-endif
 MAVEN_TEST_OPTS+= "-Djava.awt.headless=true"
 
 ifneq "$(OFFLINE)" "true"
@@ -87,13 +84,16 @@ MVN=mvn
 
 all: test
 
-symlink_pxf_jars:
+check-env:
+	@if [ -z "$(PXF_HOME)" ]; then echo 'ERROR: PXF_HOME must be set'; exit 1; fi
+
+symlink_pxf_jars: check-env
 	@if [ -d "$(PXF_HOME)/lib" ]; then \
 		rm -rf $(PXF_TMP_LIB) && \
 		mkdir -p $(PXF_TMP_LIB) && \
 		for jar in $(PXF_HOME)/lib/pxf-*.jar; do \
 			jar_name="$${jar##*/}"; \
-			if [[ $${jar_name} =~ ^pxf-[A-Za-z0-9]+(-[0-9.]+)\.jar$$ ]]; then \
+			if [[ $${jar_name} =~ ^pxf-[A-Za-z0-9]+(-[0-9.]+.*).jar$$ ]]; then \
 				link=$(PXF_TMP_LIB)/$${jar_name/$${BASH_REMATCH[1]}/}; \
 				echo "creating link $${link} -> $${jar}"; \
 				ln -sf "$${jar}" "$${link}"; \
@@ -102,7 +102,7 @@ symlink_pxf_jars:
 		touch $(PXF_TMP_LIB)/pxf-extras.jar; \
 	fi
 
-test: clean-logs symlink_pxf_jars sync_cloud_configs sync_jdbc_config
+test: check-env clean-logs symlink_pxf_jars sync_cloud_configs sync_jdbc_config
 	$(MVN) $(MAVEN_TEST_OPTS) ${MAVEN_DEBUG_OPTS} test
 
 clean: clean-logs
diff --git a/cli/go/src/pxf-cli/Makefile b/cli/go/src/pxf-cli/Makefile
--- a/cli/go/src/pxf-cli/Makefile
+++ b/cli/go/src/pxf-cli/Makefile
@@ -1,28 +1,30 @@
-.PHONY: all depend build tar install test clean help
+include ../../../../common.mk
+
+.PHONY: all depend build stage install test clean help
 .DEFAULT_GOAL := build
 
 TARGET := $(shell echo $${PWD\#\#*/})
 PXF_ROOT_DIR := $(shell cd ../../../.. && pwd)
-GO_DEP_CACHE := ${PXF_ROOT_DIR}/cli/go/pkg/dep
 PXF_SERVER_DIR := ${PXF_ROOT_DIR}/server
-PXF_STAGING_DIR := ${PXF_SERVER_DIR}/build/stage/bin
-PXF_SERVICE_SCRIPTS := ${PXF_SERVER_DIR}/pxf-service/src/scripts
-PXF_VERSION := $(shell grep version= ${PXF_SERVER_DIR}/gradle.properties | cut -d= -f2)
+PXF_CLI_DIR := ${PXF_ROOT_DIR}/cli
+PXF_VERSION ?= $(shell cat $(PXF_ROOT_DIR)/version)
+
 LDFLAGS := -ldflags "-X ${TARGET}/cmd.version=${PXF_VERSION}"
+GO_DEP_CACHE := ${PXF_ROOT_DIR}/cli/go/pkg/dep
 GOPATH := ${PXF_ROOT_DIR}/cli/go
 
 help:
 	@echo
 	@echo   "Possible targets"
-	@echo	"  - all (depend, build, test, tar, install)"
+	@echo	"  - all (depend, build, test, stage, install)"
 	@echo	"  - depend - fetch all Go dependencies"
-	@echo	"  - build - buid Go CLI and place in server/pxf-cli/go/bin/pxf-cli"
-	@echo	"  - test - runs tests for PXF Go CLI"
-	@echo	"  - install - install PXF CLI to $PXF_HOME/bin/pxf"
-	@echo	"  - tar - bundle PXF CLI along with tomcat into a single tarball"
-	@echo	"  - clean - remove pxf-cli binary from server/pxf-cli/go/bin"
+	@echo	"  - build - build pxf-cli binary"
+	@echo	"  - test - runs tests for pxf-cli binary"
+	@echo	"  - stage - install pxf-cli binary into build/stage/pxf/bin directory"
+	@echo	"  - install - install pxf-cli binary into $PXF_HOME/bin/"
+	@echo	"  - clean - remove pxf-cli binary"
 
-all: test tar install
+all: test stage install
 
 depend:
 	@if [ -d $(HOME)/.go-dep-cached-sources ] && [ ! -d ${GO_DEP_CACHE}/sources ]; then \
@@ -35,21 +37,20 @@ build: depend
 	go build -v ${LDFLAGS}
 	go install ${LDFLAGS}
 
-tar: build
-	mkdir -p ${PXF_STAGING_DIR}
-	cp ${PXF_SERVICE_SCRIPTS}/pxf-service ${PXF_STAGING_DIR}/pxf
-	cp ${GOPATH}/bin/pxf-cli ${PXF_STAGING_DIR}
+stage: test
+	mkdir -p ${PXF_CLI_DIR}/build/stage/pxf/bin
+	cp ${GOPATH}/bin/pxf-cli ${PXF_CLI_DIR}/build/stage/pxf/bin
 
 install: build
 	@if [ -z "$(PXF_HOME)" ]; then \
-		echo "ERROR: PXF_HOME is not set correctly"; exit 2; \
+		echo "ERROR: PXF_HOME is not set"; exit 2; \
 	fi
-	mkdir -p ${PXF_HOME}/bin
-	cp ${PXF_SERVICE_SCRIPTS}/pxf-service ${PXF_HOME}/bin/pxf
-	cp ${GOPATH}/bin/pxf-cli ${PXF_HOME}/bin
+	mkdir -p $(PXF_HOME)/bin
+	cp $(GOPATH)/bin/pxf-cli $(PXF_HOME)/bin
 
 test: build
 	ginkgo cmd end_to_end
 
 clean:
+	rm -rf ${PXF_CLI_DIR}/build
 	go clean -i
diff --git a/server/Makefile b/server/Makefile
--- a/server/Makefile
+++ b/server/Makefile
@@ -17,30 +17,34 @@
 #
 # protect the default target for this file from the targets in Makefile.global
 
-default: all
+include ../common.mk
 
-BUILD_PARAMS+= -DdeployPath="$(PXF_HOME)"
+default: stage-notest
+
 TOMCAT_VERSION="7.0.100"
 TOMCAT_DIR="tomcat/build"
 TOMCAT_TAR="apache-tomcat-${TOMCAT_VERSION}.tar.gz"
 TOMCAT_URL="http://archive.apache.org/dist/tomcat/tomcat-7/v${TOMCAT_VERSION}/bin/${TOMCAT_TAR}"
 
+PXF_ROOT_DIR := $(shell cd .. && pwd)
+PXF_VERSION ?= $(shell cat $(PXF_ROOT_DIR)/version)
+
 help:
 	@echo
 	@echo   "Possible targets"
-	@echo	"  - all (clean, compile, test, install, tar, doc)"
+	@echo	"  - all (clean, compile, test, stage)"
 	@echo	"  - clean - cleans the workspace of all produced artifacts"
 	@echo	"  - compile - compiles all PXF modules and builds their JAR files"
 	@echo	"  - test - runs unit tests for all PXF modules"
 	@echo	"  - install - setup PXF along with tomcat in the configured deployPath"
-	@echo	"  - tar - bundle PXF along with tomcat into a single tarball"
+	@echo	"  - stage - build PXF server and stage resulting artifacts along with tomcat for packaging"
 	@echo	"  - doc - creates aggregate javadoc under docs"
 
 all:
-	./gradlew clean tar $(BUILD_PARAMS)
+	./gradlew -Pversion=$(PXF_VERSION) clean stage
 
 compile:
-	./gradlew compileJava
+	./gradlew -Pversion=$(PXF_VERSION) compileJava
 
 GRADLEW_TEST_PARAMS = test
 ifneq "$(TEST)" ""
@@ -58,10 +62,15 @@ test unittest:
 		echo 'Test $(TEST) was not found'; \
 		exit 1; \
 	fi
-	./gradlew ${GRADLEW_TEST_PARAMS}
+	./gradlew -Pversion=$(PXF_VERSION) ${GRADLEW_TEST_PARAMS}
 
-tar: tomcat
-	./gradlew tar ${BUILD_PARAMS}
+.PHONY: stage
+stage: tomcat test
+	./gradlew -Pversion=$(PXF_VERSION) stage
+
+.PHONY: stage-notest
+stage-notest: tomcat
+	./gradlew -Pversion=$(PXF_VERSION) stage -x test
 
 clean:
 	./gradlew clean
@@ -70,7 +79,7 @@ clean:
 distclean maintainer-clean: clean
 
 doc:
-	./gradlew aggregateJavadoc
+	./gradlew -Pversion=$(PXF_VERSION) aggregateJavadoc
 
 .PHONY: tomcat
 tomcat:
@@ -101,9 +110,9 @@ tomcat:
 .PHONY: install
 install: tomcat
 	@if [ -z "$(PXF_HOME)" ]; then \
-		echo "ERROR: PXF_HOME is not set correctly"; exit 2; \
+		echo "ERROR: PXF_HOME is not set"; exit 2; \
 	fi
-	./gradlew install ${BUILD_PARAMS}
+	./gradlew -Pversion=$(PXF_VERSION) install -DdeployPath="$(PXF_HOME)"
 
 .PHONY: version
 version:
